part of 'app_pages.dart';
// Originally generated by package:get_cli, and edited by hand many times since —
// routes have been added and removed here directly. It is ordinary source now.

abstract class Routes {
  Routes._();
  static const sys= _Paths.sys;
  static const opLog= _Paths.opLog;
  static const loginLog= _Paths.loginLog;
  static const transport= _Paths.transport;
  static const distributionStatus = _Paths.distributionStatus;
  static const login = _Paths.login;
  static const products = _Paths.products;
  static const productTableDetail = _Paths.productTableDetail;
  static const warehouseInventory = _Paths.warehouseInventory;
  static const warehouseList = _Paths.warehouseList;
  static const distributionList = _Paths.distributionList;
  static const distributionApply = _Paths.distributionApply;
  static const home = _Paths.home;
}

abstract class _Paths {
  static const sys= '/sys';
  static const opLog= '/op';
  static const loginLog= '/loginlog';
  static const transport = '/transport';
  static const distributionStatus = '/distribution-status';
  static const login = '/login';
  static const distributionList = '/distribution-list';
  static const distributionApply = '/distribution-apply';
  static const warehouseList = '/warehouse-list';
  static const warehouseInventory = '/warehouse-inventory';
  static const productTableDetail = '/product-table-detail';
  static const products = '/products';
  static const home = '/home';
}
