import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// `tool/openapi.json` is committed, and springdoc fills its `servers` block with whatever
/// host produced the document. That host is somebody's machine, so the committed copy has
/// carried a home LAN address before now — for twelve commits, in a public repository,
/// until a sweep found it.
///
/// The file is regenerated by hand, so a note in the README is the wrong instrument: it asks
/// someone to remember. This asks nothing. Regenerate against any real backend, forget to
/// re-pin the host, and this is red before the commit exists.
///
/// `lib/app/data/api/README.md` has the one-liner that re-pins it as part of regenerating.
void main() {
  test('the committed OpenAPI document names no real host', () {
    final doc = jsonDecode(
      File('tool/openapi.json').readAsStringSync(),
    ) as Map<String, dynamic>;

    final servers = doc['servers'] as List<dynamic>?;
    expect(
      servers,
      isNotNull,
      reason: 'tool/openapi.json has no servers block — refresh it',
    );

    for (final server in servers!) {
      final url = (server as Map)['url'] as String;
      final host = Uri.parse(url).host;
      expect(
        host,
        anyOf('localhost', '127.0.0.1'),
        reason:
            'tool/openapi.json declares servers[].url = $url.\n'
            'That is the address of whichever backend answered when the document was '
            'generated, and this file is committed and public.\n'
            'Re-pin it with the one-liner in lib/app/data/api/README.md — it writes LF and a '
            'trailing newline, so the diff stays one line instead of the whole file.\n',
      );
    }
  });
}
